# Generated by Django 2.0.5 on 2018-06-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtocontactmap',
            old_name='user',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='phonetocontactmap',
            old_name='user',
            new_name='name',
        ),
    ]
